version: "3.9"

services:
  postgres-db:
    image: postgres:16.6-alpine
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?POSTGRES_USER is not specified}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is not specified}
      POSTGRES_DB: ${POSTGRES_DB:?POSTGRES_DB is not specified}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redisdb:
    image: redis:6.2.16-alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD:?REDIS_PASSWORD is not specified} --save 300 10
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
